q_class1_result = '   n_nationkey  n_name  n_regionkey                                          n_comment\n0            3  CANADA            1  eas hang ironic, silent packages. slyly regula...'
q_class1_shape = (1, 4)

q_class2_result = '    c_custkey  ...                                          c_comment\n0           1  ...  to the even, regular platelets. regular, ironi...\n1           8  ...  among the slyly regular theodolites kindle bli...\n2          11  ...  ckages. requests sleep slyly. quickly even pin...\n3          13  ...  ounts sleep carefully after the close frays. c...\n4          18  ...  s sleep. carefully even instructions nag furio...\n5          27  ...     about the carefully ironic pinto beans. accoun\n6          30  ...  lithely final requests. furiously unusual account\n7          32  ...   cial ideas. final, furious requests across the e\n8          36  ...  haggle. enticing, quiet platelets grow quickly...\n9          40  ...  rges impress after the slyly ironic courts. fo...\n10         42  ...  ssly according to the pinto beans: carefully s...\n11         47  ...  ions. express, ironic instructions sleep furio...\n12         48  ...  re fluffily pending foxes. pending, bold plate...\n13         64  ...  structions after the quietly ironic theodolite...\n14         73  ...  usual, unusual packages sleep busily along the...\n15         77  ...  uffily silent requests. carefully ironic asymp...\n16         81  ...  r packages. fluffily ironic requests cajole fl...\n17         83  ...  ccording to the quickly bold warhorses. final,...\n18         90  ...                     sly across the furiously even \n19         98  ...  ages. furiously pending accounts are quickly c...\n\n[20 rows x 8 columns]'

q_class2_shape = (30142, 8)

cmp_date_result = '    l_orderkey  l_partkey  ...  l_shipmode                               l_comment\n0            1     155190  ...       TRUCK                 egular courts above the\n1            1      67310  ...        MAIL      ly final dependencies: slyly bold \n2            1      63700  ...     REG AIR           riously. regular, express dep\n3            1       2132  ...         AIR                 lites. fluffily even de\n4            1      24027  ...         FOB                 pending foxes. slyly re\n5            1      15635  ...        MAIL                       arefully slyly ex\n6            2     106170  ...        RAIL         ven requests. deposits breach a\n7            3       4297  ...         AIR     ongside of the furiously brave acco\n8            3      19036  ...        RAIL                   unusual accounts. eve\n9            3     128449  ...        SHIP                        nal foxes wake. \n10           3      29380  ...       TRUCK                   y. fluffily pending d\n11           3     183095  ...         FOB                  ages nag slyly pending\n12           3      62143  ...        RAIL               ges sleep after the caref\n13           4      88035  ...     REG AIR  - quickly regular packages sleep. idly\n14           5     108570  ...         AIR                      ts wake furiously \n15           5     123927  ...         FOB   sts use slyly quickly special instruc\n16           5      37531  ...         AIR             eodolites. fluffily unusual\n17           6     139636  ...       TRUCK               p furiously special foxes\n18           7     182052  ...         FOB          ss pinto beans wake against th\n19           7     145243  ...        SHIP                        es. instructions\n\n[20 rows x 16 columns]'

cmp_date_shape = (5916591, 16)

multi_q_result = '    o_orderkey  ...                                          o_comment\n0            5  ...  quickly. bold deposits sleep slyly. packages u...\n1           64  ...  wake fluffily. sometimes ironic pinto beans ab...\n2           66  ...                       y pending requests integrate\n3           69  ...   depths atop the slyly thin deposits detect am...\n4           96  ...                              oost furiously. pinto\n5           98  ...  c asymptotes. quickly regular packages should ...\n6           99  ...               e carefully ironic packages. pending\n7          131  ...       after the fluffily special foxes integrate s\n8          161  ...                carefully! special instructions sin\n9          224  ...               r the quickly thin courts. carefully\n10         231  ...   packages haggle slyly after the carefully iro...\n11         263  ...                  pending instructions. blithely un\n12         290  ...                     efully dogged deposits. furiou\n13         291  ...       dolites. carefully regular pinto beans cajol\n14         295  ...     unusual pinto beans play. regular ideas haggle\n15         323  ...  arefully pending foxes sleep blithely. slyly e...\n16         352  ...  ke slyly bold pinto beans. blithely regular ac...\n17         355  ...  s. sometimes regular requests cajole. regular,...\n18         356  ...            as wake along the bold accounts. even, \n19         359  ...  n dolphins. special courts above the carefully...\n\n[20 rows x 9 columns]'

multi_q_shape = (227597, 9)

like_result = '    p_partkey  ...             p_comment\n0         249  ...      excuses kindle f\n1         323  ...               ular pi\n2        1015  ...     ial deposits. acc\n3        1634  ...        ven attainment\n4        2037  ...   rding to the blithe\n5        2156  ...               grouche\n6        3080  ...          , final pack\n7        3563  ...          round the fu\n8        3822  ...          ously carefu\n9        3873  ...               usly ex\n10       4020  ...    indle furiously af\n11       4081  ...                 es. d\n12       4191  ...     kly regular ideas\n13       4637  ...                 s wak\n14       4841  ...             ven reque\n15       4888  ...                 ular \n16       4958  ...        y final ideas \n17       5174  ...  ithely among the car\n18       5175  ...           ckly unusua\n19       5226  ...         nic accounts \n\n[20 rows x 9 columns]'

like_shape = (747, 9)

inlist_result = '    p_partkey  ...              p_comment\n0           4  ...          p furiously r\n1           7  ...               lyly. ex\n2          15  ...               usual ac\n3          22  ...                 even p\n4          25  ...          requests wake\n5          28  ...    x-ray pending, iron\n6          35  ...       e carefully furi\n7          36  ...               olites o\n8          42  ...               the slow\n9          45  ...                 nts bo\n10         46  ...  the blithely unusual \n11         54  ...             e blithely\n12         55  ...           ly final pac\n13         57  ...               lly abov\n14         65  ...  posits after the quic\n15         76  ...    n accounts sleep qu\n16         90  ...                  caref\n17         95  ...     final pinto beans \n18         97  ...    ss excuses sleep am\n19        103  ...       e blithely blith\n\n[20 rows x 9 columns]'

inlist_shape = (30568, 9)

or_result = '    p_partkey  ...              p_comment\n0          55  ...           ly final pac\n1         433  ...   ts haggle furiously \n2        1092  ...          y bold asympt\n3        3312  ...       furiously slyly \n4        3762  ...         deposits haggl\n5        3987  ...        he carefully re\n6        6285  ...                  nder \n7        6421  ...      tructions. dogged\n8        7088  ...        unusual excuses\n9       10857  ...       . ironically reg\n10      12087  ...         ckly bold foxe\n11      13106  ...       ideas maintain f\n12      14013  ...                side of\n13      15576  ...  ins. permanent, bold \n14      16587  ...                yly. so\n15      17036  ...               s wake b\n16      17115  ...     lites cajole blith\n17      17233  ...             ithely car\n18      17318  ...                ly pend\n19      18282  ...             regular re\n\n[20 rows x 9 columns]'

or_shape = (247, 9)



